data: 
  data: inj_cora
  dir: './data'
  batch_size: 1024
  test_split: 0.2
  max_node_num: 15
  max_feat_num: 64
  init: deg

sde:
  x: 
    type: VP
    beta_min: 0.1
    beta_max: 1.0
    num_scales: 1000
    endtime: 1
    sym: False
  adj: 
    type: VP
    beta_min: 0.1
    beta_max: 1.0
    num_scales: 1000
    endtime: 1
    sym: True

model:
  x: ScoreNetworkX
  adj: ScoreNetworkA
  conv: GCN
  num_heads: 4
  depth: 1
  adim: 32
  nhid: 32
  num_layers: 1
  num_linears: 2
  c_init: 2
  c_hid: 8
  c_final: 4
  sym: True
  
train:
  name: test
  num_epochs: 300
  save_interval: 300
  print_interval: 10
  reduce_mean: False
  lr: 0.01
  lr_schedule: False
  ema: 0.999
  weight_decay: 0.01
  grad_norm: 1.0
  lr_decay: 0.999
  eps: 1.0e-5

sampler:
  predictor: Euler
  corrector: None
  snr: 0.15
  scale_eps: 0.7
  n_steps: 1

sample:
  use_ema: False
  noise_removal: True
  probability_flow: False
  eps: 1.0e-4
  seed: 12
